/**
 * 0.5A Six-Person Combat Engine (bundled)
 * Generated by scripts/build-combat-bundle.js — edit src/ then rebuild.
 */
(function (root) {
  const __COMBAT__ = {
  "elementAdvantagePct": 0.15,
  "elementDisadvantagePct": 0.12,
  "elementCycle": { "金": "木", "木": "土", "土": "水", "水": "火", "火": "金" },
  "neutralElements": ["雷", "风"],
  "baseCritChance": 0.10,
  "baseCritDamage": 1.55,
  "defFactor": 0.45,
  "armorBreakDefFactor": 0.62,
  "burnTickPct": 0.055,
  "poisonTickPct": 0.04,
  "freezeSkipChance": 1.0,
  "slowSpeedFactor": 0.70,
  "maxRounds": 20,
  "formationActiveUses": 1,
  "masterSkillUses": 1,
  "advanceSpeedBonus": 0.35,
  "delaySpeedPenalty": 0.35,
  "energyGainBasic": 32,
  "energyCap": 100,
  "minDamage": 1,
  "timeoutIsDefeat": true
}
;
  const __STATUSES__ = {
  "shield": {
    "id": "shield",
    "name": "护盾",
    "tags": ["buff", "barrier"],
    "stackRule": "add",
    "duration": 99,
    "tick": null,
    "valueKey": "shieldHp"
  },
  "poison": {
    "id": "poison",
    "name": "中毒",
    "tags": ["debuff", "dot"],
    "stackRule": "maxStacks",
    "maxStacks": 5,
    "duration": 3,
    "tick": "poison"
  },
  "burn": {
    "id": "burn",
    "name": "燃烧",
    "tags": ["debuff", "dot"],
    "stackRule": "replace",
    "duration": 2,
    "tick": "burn"
  },
  "freeze": {
    "id": "freeze",
    "name": "冻结",
    "tags": ["debuff", "control"],
    "stackRule": "replace",
    "duration": 1,
    "tick": null,
    "skipAction": true
  },
  "slow": {
    "id": "slow",
    "name": "减速",
    "tags": ["debuff"],
    "stackRule": "replace",
    "duration": 2,
    "tick": null,
    "speedFactor": true
  },
  "armorBreak": {
    "id": "armorBreak",
    "name": "破甲",
    "tags": ["debuff"],
    "stackRule": "replace",
    "duration": 2,
    "tick": null
  },
  "taunt": {
    "id": "taunt",
    "name": "嘲讽",
    "tags": ["buff"],
    "stackRule": "replace",
    "duration": 2,
    "tick": null
  },
  "critChance": {
    "id": "critChance",
    "name": "会心提升",
    "tags": ["buff"],
    "stackRule": "add",
    "duration": 3,
    "tick": null
  },
  "critDamage": {
    "id": "critDamage",
    "name": "会伤提升",
    "tags": ["buff"],
    "stackRule": "add",
    "duration": 3,
    "tick": null
  },
  "evasion": {
    "id": "evasion",
    "name": "闪避",
    "tags": ["buff"],
    "stackRule": "replace",
    "duration": 1,
    "tick": null,
    "charges": 1
  },
  "antiHeal": {
    "id": "antiHeal",
    "name": "禁疗",
    "tags": ["debuff"],
    "stackRule": "replace",
    "duration": 2,
    "tick": null,
    "interfaceOnly": true
  },
  "advance": {
    "id": "advance",
    "name": "拉条",
    "tags": ["buff", "timeline"],
    "stackRule": "add",
    "duration": 1,
    "tick": null
  },
  "delay": {
    "id": "delay",
    "name": "推条",
    "tags": ["debuff", "timeline"],
    "stackRule": "add",
    "duration": 1,
    "tick": null
  }
}
;
  const __SKILLS__ = {
  "skillTypeMigration": {
    "guard": "skill_guard",
    "heal": "skill_heal",
    "burn": "skill_burn",
    "execute": "skill_execute",
    "thunder": "skill_thunder",
    "phoenix": "skill_phoenix",
    "evade": "skill_evade",
    "bind": "skill_bind",
    "taunt": "skill_taunt",
    "haste": "skill_haste",
    "wind": "skill_wind",
    "break": "skill_break"
  },
  "skills": {
    "basic_attack": {
      "id": "basic_attack",
      "name": "普攻",
      "slot": "basic",
      "cost": 0,
      "targetRule": "enemyFrontPrefer",
      "effects": [
        { "type": "damage", "power": 1.0, "useCrit": true }
      ]
    },
    "skill_guard": {
      "id": "skill_guard",
      "name": "镇岳式",
      "slot": "active",
      "cost": 80,
      "legacyType": "guard",
      "targetRule": "allyAll",
      "effects": [
        { "type": "shield", "stat": "def", "power": 1.35, "levelScale": 0.12, "targetRule": "allyAll" },
        { "type": "applyStatus", "statusId": "taunt", "duration": 1, "targetRule": "self" }
      ]
    },
    "skill_heal": {
      "id": "skill_heal",
      "name": "回春引",
      "slot": "active",
      "cost": 65,
      "legacyType": "heal",
      "targetRule": "allyLowestHpPct",
      "effects": [
        { "type": "heal", "power": 1.5, "levelScale": 0.14, "targetRule": "allyLowestHpPct" },
        { "type": "dispel", "tags": ["debuff"], "statusIds": ["burn"], "targetRule": "allyLowestHpPct" }
      ]
    },
    "skill_burn": {
      "id": "skill_burn",
      "name": "流火符",
      "slot": "active",
      "cost": 70,
      "legacyType": "burn",
      "targetRule": "enemyLowestHp",
      "effects": [
        { "type": "damage", "power": 1.18, "levelScale": 0.09, "useCrit": true },
        { "type": "applyStatus", "statusId": "burn", "duration": 2, "targetRule": "primary" }
      ]
    },
    "skill_execute": {
      "id": "skill_execute",
      "name": "霜河断",
      "slot": "active",
      "cost": 90,
      "legacyType": "execute",
      "targetRule": "enemyLowestHp",
      "effects": [
        { "type": "damage", "power": 1.18, "levelScale": 0.09, "executeBonus": 0.9, "useCrit": true }
      ]
    },
    "skill_thunder": {
      "id": "skill_thunder",
      "name": "惊雷踏",
      "slot": "active",
      "cost": 75,
      "legacyType": "thunder",
      "targetRule": "enemyAll",
      "effects": [
        { "type": "stripShield", "targetRule": "enemyAll" },
        { "type": "damage", "power": 0.70, "levelScale": 0.05, "defMul": 0.16, "targetRule": "enemyAll" },
        { "type": "applyStatus", "statusId": "armorBreak", "duration": 2, "targetRule": "enemyAll" }
      ]
    },
    "skill_phoenix": {
      "id": "skill_phoenix",
      "name": "赤鸾火",
      "slot": "active",
      "cost": 85,
      "legacyType": "phoenix",
      "targetRule": "enemyAll",
      "effects": [
        { "type": "damage", "power": 0.58, "levelScale": 0.05, "defMul": 0.25, "targetRule": "enemyAll" },
        { "type": "energy", "amount": 14, "levelScale": 2, "targetRule": "allyAll" }
      ]
    },
    "skill_evade": {
      "id": "skill_evade",
      "name": "藏锋",
      "slot": "active",
      "cost": 60,
      "legacyType": "evade",
      "targetRule": "enemyLowestHp",
      "effects": [
        { "type": "damage", "power": 1.15, "levelScale": 0.08, "defMul": 0.35, "useCrit": true },
        { "type": "applyStatus", "statusId": "evasion", "duration": 1, "charges": 1, "targetRule": "self" }
      ]
    },
    "skill_bind": {
      "id": "skill_bind",
      "name": "缚灵符",
      "slot": "active",
      "cost": 70,
      "legacyType": "bind",
      "targetRule": "enemyFastest",
      "effects": [
        { "type": "damage", "power": 0.72, "levelScale": 0.05, "defMul": 0.3, "useCrit": true },
        { "type": "applyStatus", "statusId": "freeze", "duration": 1, "targetRule": "primary" }
      ]
    },
    "skill_taunt": {
      "id": "skill_taunt",
      "name": "横炉",
      "slot": "active",
      "cost": 70,
      "legacyType": "taunt",
      "targetRule": "self",
      "effects": [
        { "type": "shield", "stat": "def", "power": 1.8, "levelScale": 0.18, "targetRule": "self" },
        { "type": "applyStatus", "statusId": "taunt", "duration": 2, "targetRule": "self" }
      ]
    },
    "skill_haste": {
      "id": "skill_haste",
      "name": "青雀扰",
      "slot": "active",
      "cost": 60,
      "legacyType": "haste",
      "targetRule": "allyAll",
      "effects": [
        { "type": "applyStatus", "statusId": "critChance", "duration": 3, "value": 0.10, "levelScale": 0.015, "targetRule": "allyAll" },
        { "type": "applyStatus", "statusId": "advance", "duration": 1, "value": 1, "targetRule": "allyAll" },
        { "type": "energy", "amount": 10, "targetRule": "allyAll" }
      ]
    },
    "skill_wind": {
      "id": "skill_wind",
      "name": "御风诀",
      "slot": "active",
      "cost": 70,
      "legacyType": "wind",
      "targetRule": "enemyLowestHp",
      "effects": [
        { "type": "damage", "power": 0.72, "defMul": 0.22, "useCrit": true },
        { "type": "dispel", "tags": ["debuff"], "targetRule": "allyAll" },
        { "type": "energy", "amount": 12, "targetRule": "allyAll" },
        { "type": "applyStatus", "statusId": "critChance", "duration": 2, "value": 0.08, "targetRule": "allyAll" },
        { "type": "applyStatus", "statusId": "advance", "duration": 1, "value": 1, "targetRule": "allyAll" }
      ]
    },
    "skill_break": {
      "id": "skill_break",
      "name": "破阵斩",
      "slot": "active",
      "cost": 75,
      "legacyType": "break",
      "targetRule": "enemyAll",
      "effects": [
        { "type": "damage", "power": 0.62, "levelScale": 0.05, "defMul": 0.25, "targetRule": "enemyAll" },
        { "type": "applyStatus", "statusId": "armorBreak", "duration": 2, "targetRule": "enemyAll" }
      ]
    },
    "skill_poison_sample": {
      "id": "skill_poison_sample",
      "name": "蚀骨针",
      "slot": "active",
      "cost": 55,
      "targetRule": "enemyFrontPrefer",
      "effects": [
        { "type": "damage", "power": 0.85, "useCrit": true },
        { "type": "applyStatus", "statusId": "poison", "duration": 3, "stacks": 1, "targetRule": "primary" }
      ]
    },
    "skill_slow_sample": {
      "id": "skill_slow_sample",
      "name": "滞空符",
      "slot": "active",
      "cost": 50,
      "targetRule": "enemyFastest",
      "effects": [
        { "type": "damage", "power": 0.6, "useCrit": true },
        { "type": "applyStatus", "statusId": "slow", "duration": 2, "targetRule": "primary" },
        { "type": "applyStatus", "statusId": "delay", "duration": 1, "value": 1, "targetRule": "primary" }
      ]
    },
    "formation_starter": {
      "id": "formation_starter",
      "name": "三才聚灵",
      "slot": "formation",
      "effects": [{ "type": "energy", "amount": 20, "targetRule": "allyAll" }]
    },
    "formation_earth": {
      "id": "formation_earth",
      "name": "玄岩护界",
      "slot": "formation",
      "effects": [
        { "type": "shield", "stat": "maxHp", "power": 0.28, "targetRule": "allyAll" },
        { "type": "heal", "powerPctMaxHp": 0.08, "targetRule": "allyAll" }
      ]
    },
    "formation_wood": {
      "id": "formation_wood",
      "name": "万木回春",
      "slot": "formation",
      "effects": [{ "type": "heal", "powerPctMaxHp": 0.20, "targetRule": "allyAll" }]
    },
    "formation_fire": {
      "id": "formation_fire",
      "name": "赤霞燎原",
      "slot": "formation",
      "effects": [{ "type": "applyStatus", "statusId": "burn", "duration": 3, "targetRule": "enemyAll" }]
    },
    "formation_storm": {
      "id": "formation_storm",
      "name": "天罡疾行",
      "slot": "formation",
      "effects": [
        { "type": "energy", "amount": 35, "targetRule": "allyAll" },
        { "type": "applyStatus", "statusId": "critChance", "duration": 3, "value": 0.15, "targetRule": "allyAll" }
      ]
    },
    "formation_cycle": {
      "id": "formation_cycle",
      "name": "周天轮转",
      "slot": "formation",
      "effects": [
        { "type": "heal", "powerPctMaxHp": 0.12, "targetRule": "allyAll" },
        { "type": "shield", "stat": "maxHp", "power": 0.12, "targetRule": "allyAll" },
        { "type": "energy", "amount": 20, "targetRule": "allyAll" }
      ]
    },
    "formation_sword": {
      "id": "formation_sword",
      "name": "七曜同辉",
      "slot": "formation",
      "effects": [
        { "type": "applyStatus", "statusId": "critChance", "duration": 1, "value": 0.20, "targetRule": "allyAll" },
        { "type": "energy", "amount": 22, "targetRule": "allyAll" }
      ]
    },
    "master_clear_mind": {
      "id": "master_clear_mind",
      "name": "清心令",
      "slot": "master",
      "effects": [
        { "type": "dispel", "tags": ["debuff"], "targetRule": "allyAll" },
        { "type": "energy", "amount": 18, "targetRule": "allyAll" }
      ]
    }
  },
  "formationActiveMap": {
    "starter": "formation_starter",
    "earth": "formation_earth",
    "wood": "formation_wood",
    "fire": "formation_fire",
    "storm": "formation_storm",
    "cycle": "formation_cycle",
    "sword": "formation_sword"
  }
}
;

  const __modules = Object.create(null);
  function __require(id) {
    const key = id.replace(/^\.\//, "");
    if (!__modules[key]) throw new Error("Unknown module: " + id);
    return __modules[key].exports;
  }

  
  __modules["rng"] = { exports: {} };
  (function(module, exports, require) {
    let __exports;
    /** Mulberry32 deterministic PRNG from a 32-bit seed. */
function createSeededRng(seed) {
  let t = (Number(seed) >>> 0) || 1;
  return function rng() {
    t += 0x6D2B79F5;
    let r = Math.imul(t ^ (t >>> 15), 1 | t);
    r ^= r + Math.imul(r ^ (r >>> 7), 61 | r);
    return ((r ^ (r >>> 14)) >>> 0) / 4294967296;
  };
}

__exports = { createSeededRng };

    if (__exports !== undefined) module.exports = __exports;
  })(__modules["rng"], __modules["rng"].exports, __require);
  

  __modules["targeting"] = { exports: {} };
  (function(module, exports, require) {
    let __exports;
    function living(units) {
  return (units || []).filter((u) => u.hp > 0);
}

function hasStatus(unit, statusId) {
  return (unit.statuses || []).some((s) => s.id === statusId && (s.duration == null || s.duration > 0));
}

/** Front3 preferred; taunt on opposing side overrides. */
function pickEnemyFrontPrefer(attacker, foes) {
  const alive = living(foes);
  if (!alive.length) return [];
  const taunter = alive.find((u) => hasStatus(u, "taunt"));
  if (taunter) return [taunter];
  const front = alive.filter((u) => u.position === "front");
  const pool = front.length ? front : alive;
  return [pool[0]];
}

function pickByRule(rule, actor, allies, foes, primary) {
  const a = living(allies);
  const f = living(foes);
  switch (rule) {
    case "self":
      return actor.hp > 0 ? [actor] : [];
    case "primary":
      return primary && primary.hp > 0 ? [primary] : [];
    case "enemyFrontPrefer":
      return pickEnemyFrontPrefer(actor, foes);
    case "enemyLowestHp":
      return f.length ? [f.slice().sort((x, y) => x.hp - y.hp)[0]] : [];
    case "enemyFastest":
      return f.length ? [f.slice().sort((x, y) => effectiveSpeed(y) - effectiveSpeed(x) || String(x.uid).localeCompare(String(y.uid)))[0]] : [];
    case "enemyAll":
      return f;
    case "allyAll":
      return a;
    case "allyLowestHpPct":
      return a.length
        ? [a.slice().sort((x, y) => x.hp / x.maxHp - y.hp / y.maxHp)[0]]
        : [];
    default:
      return pickEnemyFrontPrefer(actor, foes);
  }
}

function effectiveSpeed(unit, combatConfig) {
  let spd = unit.speed || 0;
  const slow = (unit.statuses || []).find((s) => s.id === "slow");
  if (slow && combatConfig) spd *= combatConfig.slowSpeedFactor;
  const adv = (unit.statuses || []).filter((s) => s.id === "advance").reduce((n, s) => n + (s.value || 1), 0);
  const del = (unit.statuses || []).filter((s) => s.id === "delay").reduce((n, s) => n + (s.value || 1), 0);
  if (combatConfig && adv) spd *= 1 + combatConfig.advanceSpeedBonus * adv;
  if (combatConfig && del) spd *= Math.max(0.05, 1 - combatConfig.delaySpeedPenalty * del);
  return spd;
}

/** Build speed queue: speed desc, tie-break by uid asc (stable). */
function buildSpeedQueue(units, combatConfig) {
  return living(units)
    .map((u) => ({ uid: u.uid, speed: effectiveSpeed(u, combatConfig) }))
    .sort((a, b) => b.speed - a.speed || String(a.uid).localeCompare(String(b.uid)));
}

__exports = {
  living,
  hasStatus,
  pickEnemyFrontPrefer,
  pickByRule,
  effectiveSpeed,
  buildSpeedQueue
};

    if (__exports !== undefined) module.exports = __exports;
  })(__modules["targeting"], __modules["targeting"].exports, __require);
  

  __modules["status"] = { exports: {} };
  (function(module, exports, require) {
    let __exports;
    const STATUSES = __STATUSES__;

function getStatusDef(statusId) {
  return STATUSES[statusId] || null;
}

function findStatus(unit, statusId) {
  return (unit.statuses || []).find((s) => s.id === statusId);
}

function applyStatus(unit, statusId, opts = {}, log) {
  const def = getStatusDef(statusId);
  if (!def) return;
  if (!unit.statuses) unit.statuses = [];
  const duration = opts.duration != null ? opts.duration : def.duration;
  const value = opts.value != null ? opts.value : 0;
  const stacks = opts.stacks != null ? opts.stacks : 1;
  const charges = opts.charges != null ? opts.charges : def.charges;

  if (statusId === "shield") {
    const add = Math.max(0, Math.round(opts.shieldHp || value || 0));
    unit.shieldHp = (unit.shieldHp || 0) + add;
    const existing = findStatus(unit, "shield");
    if (existing) {
      existing.shieldHp = unit.shieldHp;
      existing.duration = Math.max(existing.duration || 0, duration || 99);
    } else {
      unit.statuses.push({ id: "shield", duration: duration || 99, shieldHp: unit.shieldHp, tags: def.tags });
    }
    if (log && add) log.push(`${unit.name}获得${add}点护盾。`);
    return;
  }

  const existing = findStatus(unit, statusId);
  const entry = {
    id: statusId,
    duration,
    value,
    stacks,
    charges,
    tags: def.tags ? [...def.tags] : []
  };

  if (!existing) {
    unit.statuses.push(entry);
    if (log) log.push(`${unit.name}获得「${def.name}」。`);
    return;
  }

  if (def.stackRule === "replace") {
    Object.assign(existing, entry);
    if (log) log.push(`${unit.name}刷新「${def.name}」。`);
  } else if (def.stackRule === "add") {
    existing.duration = Math.max(existing.duration || 0, duration || 0);
    existing.value = (existing.value || 0) + (value || 0);
    existing.stacks = (existing.stacks || 0) + stacks;
    if (charges != null) existing.charges = (existing.charges || 0) + charges;
    if (log) log.push(`${unit.name}叠加「${def.name}」。`);
  } else if (def.stackRule === "maxStacks") {
    existing.stacks = Math.min(def.maxStacks || 99, (existing.stacks || 0) + stacks);
    existing.duration = Math.max(existing.duration || 0, duration || 0);
    if (log) log.push(`${unit.name}「${def.name}」层数${existing.stacks}。`);
  } else {
    Object.assign(existing, entry);
  }
}

function dispelStatuses(unit, opts = {}, log) {
  const tags = opts.tags || [];
  const statusIds = opts.statusIds || [];
  const kept = [];
  const removed = [];
  for (const s of unit.statuses || []) {
    const def = getStatusDef(s.id) || s;
    const stags = def.tags || s.tags || [];
    let remove = false;
    if (statusIds.length && statusIds.includes(s.id)) remove = true;
    if (tags.length && tags.some((t) => stags.includes(t))) remove = true;
    if (remove) removed.push(s);
    else kept.push(s);
  }
  unit.statuses = kept;
  if (removed.some((s) => s.id === "shield")) unit.shieldHp = 0;
  if (log && removed.length) {
    log.push(`${unit.name}被驱散：${removed.map((s) => (getStatusDef(s.id) || s).name || s.id).join("、")}。`);
  }
  return removed;
}

function absorbDamageWithShield(unit, damage) {
  let remaining = Math.max(0, damage);
  const shield = unit.shieldHp || 0;
  if (shield <= 0) return { dealt: remaining, blocked: 0 };
  const blocked = Math.min(shield, remaining);
  unit.shieldHp = shield - blocked;
  remaining -= blocked;
  const sh = findStatus(unit, "shield");
  if (sh) {
    sh.shieldHp = unit.shieldHp;
    if (unit.shieldHp <= 0) unit.statuses = unit.statuses.filter((s) => s.id !== "shield");
  }
  return { dealt: remaining, blocked };
}

function tickDot(unit, status, combatConfig, log) {
  if (status.id === "burn") {
    const dmg = Math.max(1, Math.round(unit.maxHp * combatConfig.burnTickPct));
    unit.hp = Math.max(0, unit.hp - dmg);
    if (log) log.push(`${unit.name}受到${dmg}点燃烧伤害。`);
    return dmg;
  }
  if (status.id === "poison") {
    const stacks = status.stacks || 1;
    const dmg = Math.max(1, Math.round(unit.maxHp * combatConfig.poisonTickPct * stacks));
    unit.hp = Math.max(0, unit.hp - dmg);
    if (log) log.push(`${unit.name}受到${dmg}点中毒伤害（${stacks}层）。`);
    return dmg;
  }
  return 0;
}

function tickStatusesAtRoundStart(units, combatConfig, log) {
  let total = 0;
  for (const unit of units) {
    if (unit.hp <= 0) continue;
    const next = [];
    for (const status of unit.statuses || []) {
      const def = getStatusDef(status.id);
      if (def && def.tick) total += tickDot(unit, status, combatConfig, log);
      if (status.id === "shield") {
        if ((unit.shieldHp || 0) > 0) next.push(status);
        continue;
      }
      if (status.duration == null) {
        next.push(status);
        continue;
      }
      const dur = status.duration - 1;
      if (dur > 0) next.push({ ...status, duration: dur });
    }
    unit.statuses = next;
    if (unit.hp <= 0 && log) log.push(`${unit.name}倒下。`);
  }
  return total;
}

function consumeActionSkip(unit, combatConfig, rng, log) {
  const freeze = findStatus(unit, "freeze");
  if (!freeze) return false;
  const skip = rng() < combatConfig.freezeSkipChance;
  unit.statuses = (unit.statuses || []).filter((s) => s.id !== "freeze");
  if (skip && log) log.push(`${unit.name}被冻结，跳过行动。`);
  return skip;
}

function tryConsumeEvasion(unit, log, attackerName) {
  const eva = findStatus(unit, "evasion");
  if (!eva) return false;
  const charges = (eva.charges == null ? 1 : eva.charges) - 1;
  if (charges <= 0) unit.statuses = unit.statuses.filter((s) => s.id !== "evasion");
  else eva.charges = charges;
  if (log) log.push(`${unit.name}避开了${attackerName}的攻击。`);
  return true;
}

function getCritChanceBonus(unit) {
  return (unit.statuses || [])
    .filter((s) => s.id === "critChance")
    .reduce((n, s) => n + (s.value || 0), 0);
}

function getCritDamageBonus(unit) {
  return (unit.statuses || [])
    .filter((s) => s.id === "critDamage")
    .reduce((n, s) => n + (s.value || 0), 0);
}

function hasArmorBreak(unit) {
  return !!(unit.statuses || []).find((s) => s.id === "armorBreak");
}

function clearTimelineMarkers(units) {
  for (const unit of units) {
    if (!unit.statuses) continue;
    unit.statuses = unit.statuses.filter((s) => s.id !== "advance" && s.id !== "delay");
  }
}

__exports = {
  STATUSES,
  getStatusDef,
  applyStatus,
  dispelStatuses,
  absorbDamageWithShield,
  tickStatusesAtRoundStart,
  consumeActionSkip,
  tryConsumeEvasion,
  getCritChanceBonus,
  getCritDamageBonus,
  hasArmorBreak,
  clearTimelineMarkers,
  findStatus
};

    if (__exports !== undefined) module.exports = __exports;
  })(__modules["status"], __modules["status"].exports, __require);
  

  __modules["skills"] = { exports: {} };
  (function(module, exports, require) {
    let __exports;
    const SKILL_DATA = __SKILLS__;
const targeting = require("./targeting");
const status = require("./status");

function getSkill(skillId) {
  return SKILL_DATA.skills[skillId] || null;
}

function skillIdFromLegacyType(skillType) {
  return SKILL_DATA.skillTypeMigration[skillType] || null;
}

function elementMultiplier(attackerEl, defenderEl, combatConfig) {
  const neutrals = combatConfig.neutralElements || [];
  if (neutrals.includes(attackerEl) || neutrals.includes(defenderEl)) return 1;
  const cycle = combatConfig.elementCycle || {};
  if (!cycle[attackerEl] || !cycle[defenderEl]) return 1;
  if (cycle[attackerEl] === defenderEl) return 1 + combatConfig.elementAdvantagePct;
  if (cycle[defenderEl] === attackerEl) return 1 - combatConfig.elementDisadvantagePct;
  return 1;
}

function recordStat(battle, unit, key, amount) {
  if (!battle.stats) return;
  const side = unit.side === "ally" || unit.side === "player" ? "allies" : "enemies";
  if (!battle.stats[side][unit.uid]) {
    battle.stats[side][unit.uid] = { damage: 0, healing: 0, taken: 0, name: unit.name };
  }
  battle.stats[side][unit.uid][key] += amount;
}

function dealDamage(battle, attacker, target, raw, combatConfig, log, label, opts = {}) {
  if (!target || target.hp <= 0) return 0;
  if (status.tryConsumeEvasion(target, log, attacker.name)) return 0;

  let amount = raw;
  const elMul = opts.skipElement ? 1 : elementMultiplier(attacker.element, target.element, combatConfig);
  amount *= elMul;

  let crit = false;
  if (opts.useCrit) {
    const chance = combatConfig.baseCritChance + status.getCritChanceBonus(attacker) + (attacker.critChance || 0);
    if (battle.rng() < chance) {
      crit = true;
      amount *= combatConfig.baseCritDamage + status.getCritDamageBonus(attacker);
    }
  }

  let defMul = combatConfig.defFactor;
  if (opts.defMul != null) defMul = opts.defMul;
  let def = target.def * defMul;
  if (status.hasArmorBreak(target)) def *= combatConfig.armorBreakDefFactor;

  let damage = Math.max(combatConfig.minDamage, Math.round(amount - def));
  const absorbed = status.absorbDamageWithShield(target, damage);
  damage = absorbed.dealt;
  target.hp = Math.max(0, target.hp - damage);
  recordStat(battle, attacker, "damage", damage + absorbed.blocked);
  recordStat(battle, target, "taken", damage);
  const critText = crit ? "会心·" : "";
  log.push(`${attacker.name}${critText}${label || "出手"}，对${target.name}造成${damage}伤害${absorbed.blocked ? `（护盾抵挡${absorbed.blocked}）` : ""}。`);
  if (target.hp <= 0) log.push(`${target.name}倒下。`);
  return damage;
}

function healUnit(battle, healer, target, amount, log, antiHealCheck = true) {
  if (!target || target.hp <= 0) return 0;
  if (antiHealCheck && status.findStatus(target, "antiHeal")) {
    log.push(`${target.name}处于禁疗，治疗无效。`);
    return 0;
  }
  const healed = Math.max(0, Math.round(amount));
  const before = target.hp;
  target.hp = Math.min(target.maxHp, target.hp + healed);
  const actual = target.hp - before;
  recordStat(battle, healer, "healing", actual);
  log.push(`${healer.name}治疗${target.name} ${actual}点。`);
  return actual;
}

function resolveEffect(effect, ctx) {
  const { battle, actor, allies, foes, skill, combatConfig, log, primary, level } = ctx;
  const rule = effect.targetRule || skill.targetRule || "enemyFrontPrefer";
  const targets = targeting.pickByRule(rule, actor, allies, foes, primary);
  const lvl = level || 1;

  switch (effect.type) {
    case "damage": {
      for (const t of targets) {
        let power = effect.power || 1;
        if (effect.levelScale) power += effect.levelScale * (lvl - 1);
        if (effect.executeBonus) power += (1 - t.hp / t.maxHp) * effect.executeBonus;
        const raw = actor.atk * power;
        dealDamage(battle, actor, t, raw, combatConfig, log, `施展${skill.name}`, {
          useCrit: !!effect.useCrit,
          defMul: effect.defMul,
          skipElement: effect.skipElement
        });
      }
      break;
    }
    case "heal": {
      for (const t of targets) {
        let amount;
        if (effect.powerPctMaxHp != null) amount = t.maxHp * effect.powerPctMaxHp;
        else {
          let power = effect.power || 1;
          if (effect.levelScale) power += effect.levelScale * (lvl - 1);
          amount = actor.atk * power;
        }
        healUnit(battle, actor, t, amount, log);
      }
      break;
    }
    case "shield": {
      for (const t of targets) {
        let power = effect.power || 1;
        if (effect.levelScale) power += effect.levelScale * (lvl - 1);
        const stat = effect.stat === "maxHp" ? t.maxHp : effect.stat === "atk" ? actor.atk : actor.def;
        status.applyStatus(t, "shield", { shieldHp: stat * power }, log);
      }
      break;
    }
    case "applyStatus": {
      for (const t of targets) {
        let value = effect.value || 0;
        if (effect.levelScale && effect.value != null) value = effect.value + effect.levelScale * (lvl - 1);
        status.applyStatus(t, effect.statusId, {
          duration: effect.duration,
          value,
          stacks: effect.stacks,
          charges: effect.charges
        }, log);
      }
      break;
    }
    case "dispel": {
      for (const t of targets) status.dispelStatuses(t, { tags: effect.tags, statusIds: effect.statusIds }, log);
      break;
    }
    case "energy": {
      const cap = combatConfig.energyCap;
      for (const t of targets) {
        let amt = effect.amount || 0;
        if (effect.levelScale) amt += effect.levelScale * (lvl - 1);
        t.energy = Math.min(cap, (t.energy || 0) + amt);
      }
      if (targets.length) log.push(`${actor.name}为友方回复灵力。`);
      break;
    }
    case "stripShield": {
      for (const t of targets) {
        t.shieldHp = 0;
        status.dispelStatuses(t, { statusIds: ["shield"] }, log);
      }
      break;
    }
    default:
      break;
  }
}

function resolveSkill(battle, actor, skillId, combatConfig, log) {
  const skill = getSkill(skillId);
  if (!skill) {
    log.push(`${actor.name}技能配置缺失：${skillId}`);
    return;
  }
  const allies = actor.side === "enemy" ? battle.enemies : battle.allies;
  const foes = actor.side === "enemy" ? battle.allies : battle.enemies;
  const primaryTargets = targeting.pickByRule(skill.targetRule || "enemyFrontPrefer", actor, allies, foes);
  const primary = primaryTargets[0] || null;
  const level = actor.skillLevel || 1;
  const ctx = { battle, actor, allies, foes, skill, combatConfig, log, primary, level };

  if (skill.cost > 0) actor.energy = 0;
  log.push(`${actor.name}施展【${skill.name}】。`);
  for (const effect of skill.effects || []) resolveEffect(effect, ctx);
}

function chooseSkillId(unit) {
  const activeId = unit.skills && unit.skills.active;
  const cost = activeId ? (getSkill(activeId)?.cost || 0) : 999;
  if (activeId && (unit.energy || 0) >= cost) return activeId;
  return (unit.skills && unit.skills.basic) || "basic_attack";
}

__exports = {
  SKILL_DATA,
  getSkill,
  skillIdFromLegacyType,
  elementMultiplier,
  resolveSkill,
  chooseSkillId,
  dealDamage,
  healUnit
};

    if (__exports !== undefined) module.exports = __exports;
  })(__modules["skills"], __modules["skills"].exports, __require);
  

  __modules["engine"] = { exports: {} };
  (function(module, exports, require) {
    let __exports;
    const COMBAT = __COMBAT__;
const { createSeededRng } = require("./rng");
const targeting = require("./targeting");
const status = require("./status");
const skills = require("./skills");

const clone = (v) => JSON.parse(JSON.stringify(v));

function normalizeUnit(raw, side, index) {
  const position = raw.position || (index < 3 ? "front" : "back");
  const legacy = raw.skillType;
  const active =
    raw.skills?.active ||
    (legacy ? skills.skillIdFromLegacyType(legacy) : null) ||
    "basic_attack";
  return {
    uid: raw.uid || `${side}-${raw.id || index}`,
    id: raw.id || `${side}-${index}`,
    name: raw.name || raw.id || `${side}-${index}`,
    side,
    position,
    element: raw.element || "土",
    role: raw.role || "",
    tags: raw.tags || [],
    maxHp: raw.maxHp,
    hp: raw.hp != null ? raw.hp : raw.maxHp,
    atk: raw.atk,
    def: raw.def,
    speed: raw.speed,
    baseSpeed: raw.speed,
    energy: raw.energy != null ? raw.energy : 20,
    skillLevel: raw.skillLevel || 1,
    skills: {
      basic: raw.skills?.basic || "basic_attack",
      active,
      ultimate: raw.skills?.ultimate || null,
      passive: raw.skills?.passive || null
    },
    skillType: legacy || null,
    statuses: raw.statuses ? clone(raw.statuses) : [],
    shieldHp: raw.shieldHp || raw.shield || 0,
    critChance: raw.critChance || 0
  };
}

/**
 * @param {object} config EncounterConfig
 */
function createEncounter(config = {}) {
  const seed = config.seed != null ? config.seed : 42;
  const allies = (config.allies || []).map((u, i) => normalizeUnit(u, "ally", i));
  const enemies = (config.enemies || []).map((u, i) => normalizeUnit(u, "enemy", i));
  const formationId = config.formationId || "starter";
  const combatConfig = { ...COMBAT, ...(config.combatOverrides || {}) };
  return {
    engineVersion: "0.5A",
    id: config.id || "sandbox",
    name: config.name || "战斗沙盒",
    seed,
    rngState: seed,
    round: 0,
    maxRounds: config.maxRounds != null ? config.maxRounds : combatConfig.maxRounds,
    allies,
    enemies,
    formationId,
    formationActiveUses: combatConfig.formationActiveUses,
    masterSkillUses: combatConfig.masterSkillUses,
    formationReady: true,
    masterReady: true,
    environmentRules: config.environmentRules || [],
    playerCommandsAllowed: config.playerCommandsAllowed !== false,
    log: [`【0.5A】${config.name || "战斗沙盒"}开战（seed=${seed}）。`],
    combatLog: [],
    queue: [],
    finished: false,
    victory: false,
    stats: { allies: {}, enemies: {} },
    combatConfig
  };
}

function attachRng(battle) {
  if (!battle._rng) {
    // re-seed from battle.seed + round for stepwise reproducibility when cloning
    battle._rng = createSeededRng(battle.seed + battle.round * 9973);
  }
  battle.rng = battle._rng;
}

function checkFinished(battle) {
  const alliesAlive = battle.allies.some((u) => u.hp > 0);
  const enemiesAlive = battle.enemies.some((u) => u.hp > 0);
  if (!enemiesAlive && alliesAlive) {
    battle.finished = true;
    battle.victory = true;
    battle.log.unshift("战斗胜利。");
    return true;
  }
  if (!alliesAlive) {
    battle.finished = true;
    battle.victory = false;
    battle.log.unshift("我方全灭，战斗失败。");
    return true;
  }
  if (battle.round >= battle.maxRounds) {
    battle.finished = true;
    battle.victory = battle.combatConfig.timeoutIsDefeat ? false : alliesAlive && !enemiesAlive;
    battle.log.unshift(battle.victory ? "回合上限内歼敌。" : "回合上限，判负。");
    return true;
  }
  return false;
}

function getTimeline(battle) {
  return targeting.buildSpeedQueue([...battle.allies, ...battle.enemies], battle.combatConfig);
}

function useFormationActive(source) {
  const battle = clone(source);
  delete battle._rng;
  if (!battle || battle.finished || !battle.formationReady || battle.formationActiveUses <= 0) return battle;
  const map = skills.SKILL_DATA.formationActiveMap || {};
  const skillId = map[battle.formationId] || map.starter;
  battle.formationReady = false;
  battle.formationActiveUses -= 1;
  const log = [];
  const actor = {
    name: "阵法",
    side: "ally",
    atk: 0,
    def: 0,
    element: "土",
    hp: 1,
    statuses: [],
    skillLevel: 1
  };
  // Resolve as if ally caster with ally/enemy sides
  const fakeBattle = battle;
  fakeBattle.rng = createSeededRng(battle.seed + 17);
  skills.resolveSkill(fakeBattle, { ...actor, uid: "formation", skills: {} }, skillId, battle.combatConfig, log);
  // Manual: resolveSkill expects actor.side ally/enemy for ally/foe pick — formation actor side ally is fine
  battle.log = [...log, `阵法发动：${skills.getSkill(skillId)?.name || skillId}。`, ...battle.log].slice(0, 40);
  battle.combatLog = [...battle.combatLog, ...log];
  return battle;
}

function useMasterSkill(source) {
  const battle = clone(source);
  delete battle._rng;
  if (!battle || battle.finished || !battle.masterReady || battle.masterSkillUses <= 0) return battle;
  battle.masterReady = false;
  battle.masterSkillUses -= 1;
  const log = [];
  const actor = { name: "掌门", side: "ally", uid: "master", atk: 0, def: 0, element: "土", hp: 1, statuses: [], skillLevel: 1, skills: {} };
  battle.rng = createSeededRng(battle.seed + 19);
  skills.resolveSkill(battle, actor, "master_clear_mind", battle.combatConfig, log);
  battle.log = [...log, "掌门技·清心令。", ...battle.log].slice(0, 40);
  battle.combatLog = [...battle.combatLog, ...log];
  return battle;
}

/**
 * Run one full round with speed queue.
 * @param {object} sourceBattle
 * @param {object} input optional { skillOverrides: { [uid]: skillId } }
 */
function runRound(sourceBattle, input = {}) {
  const battle = clone(sourceBattle);
  delete battle._rng;
  if (!battle || battle.finished) return battle;
  battle.round += 1;
  attachRng(battle);
  const log = [`— 第${battle.round}轮（速度队列）—`];
  const cfg = battle.combatConfig;

  status.tickStatusesAtRoundStart([...battle.allies, ...battle.enemies], cfg, log);
  if (checkFinished(battle)) {
    battle.log = [...log, ...battle.log].slice(0, 40);
    return battle;
  }

  const queue = targeting.buildSpeedQueue([...battle.allies, ...battle.enemies], cfg);
  battle.queue = queue;
  log.push(`行动顺序：${queue.map((q) => q.uid).join(" → ")}`);

  for (const entry of queue) {
    if (checkFinished(battle)) break;
    const unit = [...battle.allies, ...battle.enemies].find((u) => u.uid === entry.uid);
    if (!unit || unit.hp <= 0) continue;
    if (status.consumeActionSkip(unit, cfg, battle.rng, log)) continue;

    const skillId =
      (input.skillOverrides && input.skillOverrides[unit.uid]) ||
      skills.chooseSkillId(unit);
    skills.resolveSkill(battle, unit, skillId, cfg, log);

    if (skillId === "basic_attack" || skillId === (unit.skills && unit.skills.basic)) {
      unit.energy = Math.min(cfg.energyCap, (unit.energy || 0) + cfg.energyGainBasic);
    }
  }

  status.clearTimelineMarkers([...battle.allies, ...battle.enemies]);
  checkFinished(battle);
  battle.log = [...log, ...battle.log].slice(0, 40);
  battle.combatLog = [...battle.combatLog, ...log];
  return battle;
}

/** Alias step → runRound for API compatibility. */
function step(battle, input) {
  return runRound(battle, input);
}

function runUntilDone(sourceBattle, input = {}, safety = 40) {
  let battle = sourceBattle;
  let n = 0;
  while (battle && !battle.finished && n < safety) {
    battle = runRound(battle, input);
    n += 1;
  }
  return battle;
}

function createSandboxPresets() {
  const mk = (id, name, element, stats, skillsSpec, position) => ({
    id, name, element, position, ...stats, skills: skillsSpec, skillLevel: 1
  });
  return {
    balanced: {
      id: "sandbox-balanced",
      name: "均衡对照",
      seed: 20260905,
      formationId: "starter",
      allies: [
        mk("tank", "方砚·测", "土", { maxHp: 420, atk: 55, def: 48, speed: 72, energy: 80 }, { basic: "basic_attack", active: "skill_guard" }, "front"),
        mk("healer", "顾念·测", "木", { maxHp: 280, atk: 48, def: 28, speed: 84, energy: 70 }, { basic: "basic_attack", active: "skill_heal" }, "front"),
        mk("dps", "苏晚·测", "火", { maxHp: 250, atk: 78, def: 24, speed: 95, energy: 70 }, { basic: "basic_attack", active: "skill_burn" }, "front"),
        mk("sword", "青璃·测", "水", { maxHp: 300, atk: 100, def: 32, speed: 110, energy: 90 }, { basic: "basic_attack", active: "skill_execute" }, "back"),
        mk("thunder", "玄川·测", "雷", { maxHp: 320, atk: 96, def: 36, speed: 108, energy: 80 }, { basic: "basic_attack", active: "skill_thunder" }, "back"),
        mk("wind", "天衡·测", "风", { maxHp: 290, atk: 88, def: 30, speed: 120, energy: 70 }, { basic: "basic_attack", active: "skill_wind" }, "back")
      ],
      enemies: [
        mk("e1", "灰脊狼甲", "土", { maxHp: 380, atk: 55, def: 22, speed: 70, energy: 0 }, { basic: "basic_attack", active: "basic_attack" }, "front"),
        mk("e2", "灰脊狼乙", "土", { maxHp: 380, atk: 55, def: 22, speed: 68, energy: 0 }, { basic: "basic_attack", active: "basic_attack" }, "front"),
        mk("e3", "噬灵藤", "木", { maxHp: 450, atk: 48, def: 26, speed: 55, energy: 0 }, { basic: "basic_attack", active: "skill_poison_sample" }, "back")
      ]
    },
    elementLab: {
      id: "sandbox-element",
      name: "五行实验室",
      seed: 1001,
      allies: [
        mk("metal", "金攻手", "金", { maxHp: 300, atk: 100, def: 20, speed: 100, energy: 0 }, { basic: "basic_attack", active: "basic_attack" }, "front")
      ],
      enemies: [
        mk("wood", "木靶", "木", { maxHp: 500, atk: 10, def: 20, speed: 10, energy: 0 }, { basic: "basic_attack", active: "basic_attack" }, "front")
      ]
    }
  };
}

__exports = {
  COMBAT,
  createEncounter,
  runRound,
  step,
  runUntilDone,
  useFormationActive,
  useMasterSkill,
  getTimeline,
  createSandboxPresets,
  elementMultiplier: skills.elementMultiplier,
  normalizeUnit
};

    if (__exports !== undefined) module.exports = __exports;
  })(__modules["engine"], __modules["engine"].exports, __require);
  

  __modules.index = { exports: {} };
  (function(module, exports, require) {
    const engine = require("./engine");
    const status = require("./status");
    const skills = require("./skills");
    const targeting = require("./targeting");
    const { createSeededRng } = require("./rng");
    const Combat05A = Object.assign({
      version: "0.5A",
      status, skills, targeting, createSeededRng,
      COMBAT: __COMBAT__, STATUSES: __STATUSES__, SKILLS: __SKILLS__
    }, engine);
    module.exports = Combat05A;
  })(__modules.index, __modules.index.exports, __require);

  const Combat05A = __modules.index.exports;
  root.SectCombat05A = Combat05A;
  if (typeof module !== "undefined" && module.exports) module.exports = Combat05A;
})(typeof globalThis !== "undefined" ? globalThis : this);
